ARG from_image
FROM ${from_image}

RUN uname -a
RUN apk add ruby ruby-dev ruby-rake git build-base

RUN ruby --version
RUN gem env
RUN gem inst bundler

WORKDIR /build

CMD ruby -e "puts Gem::Platform.local.to_s" && \
  gem install --local *.gem --verbose --no-document && \
  cd test/rcd_test/ && \
  bundle install && \
  rake test
